### ISSUE TITLE
Breaking change in tdqm version 4.18

### ISSUE THREAD

**Issue by brycefisher** [choldgraf/download#10]
I'm using the awesome `download` package in my own project as a library. I love it! Thank you so much.

Sadly, a few days ago, `download` stopped working for me due a breaking change in a minor version of the `tdqm` dependency at version 4.18. See https://github.com/tqdm/tqdm/issues/457. `tdqm` provides the very awesome progressbar which is enabled by default.

In my project, I'm disabling the kwarg `progressbar`, but it might be good to update the code which interacts with `tdqm` and then set a minimum version of `tdqm` in this package's requirements.txt. I can take a stab at that if you like -- let me know if you'd like a pr for this.

**Comment by choldgraf** [comment]
yes! thanks for catching this regression...PRs are definitely welcome :-)
