### ISSUE TITLE
travis-ci fail at ftp test

### ISSUE THREAD

**Issue by ferion11** [choldgraf/download#19]
There is many reports about the travis-ci fail to test ftp:
* [The Tale of FTP at Travis CI](https://blog.travis-ci.com/2018-07-23-the-tale-of-ftp-at-travis-ci)
* [python issue35411](https://bugs.python.org/issue35411)
* [curl bug report at travis-ci.community](https://travis-ci.community/t/curl-to-ftp-gnu-org-gets-retr-response-425/5889)
* [kontena issue 3361](https://github.com/kontena/kontena/issues/3361)

The workaround at this time is to avoid using ftp links on travis-ci. Maybe another way to test ftp downloads will do too (like one mock ftp server).

**Comment by choldgraf** [comment]
fixed in https://github.com/choldgraf/download/pull/20
