### ISSUE TITLE
sometimes download file only have 7.28k

### ISSUE THREAD

**Issue by jasonyun** [choldgraf/download#23]
some time download file incomplete,only have 7.28kb?

**Comment by ferion11** [comment]
I'm also interested in that too. So I was going to explain, but I decided to make the pull request about it right away. Here: https://github.com/choldgraf/download/pull/24

**Comment by jasonyun** [comment]
I can get the file size in my way, can be helped ?

**Comment by ferion11** [comment]
> I can get the file size in my way, can be helped ?

Sorry, but I don't think that I have understood what you want. Would it be something like this:
```
#!/usr/bin/env python

from urllib.request import urlopen

link =  "https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.6.tar.xz"
site = urlopen(link)
meta = site.info()
file_size = int(meta.get("Content-Length", "1").strip())
print("=== All info ===")
print(meta)
print("=== file_size only ===")
print(file_size)
```
?

**Comment by jasonyun** [comment]
no. 
I want to say that I can get the file size in my way.
I do not know if it can help solve this problem that downloading file incomplete only have 7.28kb

**Comment by ferion11** [comment]
> no.
> I want to say that I can get the file size in my way.
> I do not know if it can help solve this problem that downloading file incomplete only have 7.28kb

Well, if you have an easy way to reproduce the issue, it would be of great help.
I only encounter this issue randomly and rarely.

**Comment by ferion11** [comment]
@jasonyun , now the code make one verification before rename the file to the final name (without the ".part"):
https://github.com/choldgraf/download/blob/958615c80d19ac962316881d61411ea84f2009f6/download/download.py#L262-L268
If you find this issue, then you can just wait a little and try to re-download the file again (the download will be resumed).

**Comment by jasonyun** [comment]
I found the problem is caused by not logging in.When I use requests package add headers have 'Cookie' that have 'DomAuthSessId' data it can be download complete.Can solve the problem？

**Comment by choldgraf** [comment]
I believe this should now be fixed thanks to @CrafterKolyan - thanks for the help and glad you got it working!
