### ISSUE TITLE
Error: local variable 'remote_file_size' referenced before assignment

### ISSUE THREAD

**Issue by choldgraf** [choldgraf/download#26]
After a recent PR #24 , I'm running into this error that, for some reason, wasn't popping up in the tests and docs in the PR. My bad on that one.

@ferion11 I think that this is because `remote_file_size` is defined in a `try:` block, while logic later in the function expects `remote_file_size` to exist. Would you mind spot-checking a PR to fix this issue? I should have caught it in the original PR

**Comment by choldgraf** [comment]
(note: we didn't notice this because the docs were failing for a different reason, and when I fixed that, this bug popped up...so if you like, you can also just make a PR to my branch in this pr: #25 and we should be able to tell if the bug is fixed)

**Comment by ferion11** [comment]
ok! I'm looking at that now.

**Comment by ferion11** [comment]
Done here: https://github.com/choldgraf/download/pull/27
