### ISSUE TITLE
No tests for python 3.7, 3.8 and 2.7

### ISSUE THREAD

**Issue by CrafterKolyan** [choldgraf/download#38]
This library is said to be working everywhere. Does it mean that Python 2.7 is supported? For correct support tests should be created

**Comment by choldgraf** [comment]
it was once supported, but has been a long time since I've done a deep dive (since before 3.7 was out, in fact). I'm fine testing this on a matrix of 3.6/7/8. I'm a bit more hesitant to support 2.7 unless we think it won't change much in the codebase
